language: ruby
rvm:
- 2.4.1
sudo: required

services:
  - docker
  - memcached

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

install:
  - travis_retry bundle install

before_script:
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - cd vendor && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter

script:
  - bundle exec rspec spec
  - bundle exec codeclimate-test-reporter

after_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - export REPO=crosscite/doi-metadata-search;
  - if [ "${TRAVIS_TAG?}" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .;
      docker push $REPO:$TRAVIS_TAG;
      echo "Pushed to" $REPO:$TRAVIS_TAG;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -f Dockerfile -t $REPO .;
      docker push $REPO;
      echo "Pushed to" $REPO;
    else
      docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .;
      docker push $REPO:$TRAVIS_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_BRANCH;
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
