language: ruby
cache: bundler
sudo: required
rvm:
  - 2.4.1

services:
  - docker

before_install:
  - gem update --system
  - gem --version

before_script:
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - cd vendor && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter

script:
  - bundle exec rspec

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    export REPO=crosscite/doi-metadata-search;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker push $REPO:$COMMIT;
    fi

addons:
  code_climate:
    repo_token: 477bc3dabff86493ea83d7051e498f64ab924aa2d4697c89249e89be60d1abc1

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
