development_links:
 - name: Homepage
   url: http://localhost:8060
   icon: globe
 - name: Blog
   url: http://localhost:8030
   icon: rss
 - name: Assets
   url: http://localhost:8010
   icon: file-image-o
 - name: Profiles
   url: http://localhost:8080
   icon: user
 - name: divider
 - name: MDS
   url: https://mds.test.datacite.org
   icon: database
 - name: Schema
   url: http://localhost:8020
   icon: file-code-o
 - name: Event Data
   url: http://localhost:8050
   icon: link
 - name: Citation Formatter
   url: http://localhost:9020
   icon: file-text-o
 - name: divider
 - name: Search
   url: http://localhost:8000
   icon: search
 - name: OAI-PMH
   url: http://localhost:9030
   icon: table
 - name: Statistics
   url: http://localhost:9010
   icon: bar-chart
 - name: REST API
   url: http://localhost:8040
   icon: cogs
stage_links:
 - name: MDS
   url: https://mds.test.datacite.org
   icon: database
 - name: Schema
   url: https://schema.test.datacite.org
   icon: file-code-o
 - name: Handle Server
   url: https://handle.test.datacite.org
   icon: mail-forward
 - name: Citation Formatter
   url: http://citation.test.crosscite.org
   icon: file-text-o
 - name: divider
 - name: Search
   url: https://search.test.datacite.org
   icon: search
 - name: OAI-PMH
   url: https://oai.test.datacite.org
   icon: table
 - name: Statistics
   url: https://stats.test.datacite.org
   icon: bar-chart
 - name: REST API
   url: https://api.test.datacite.org
   icon: cogs
production_links:
 - name: Homepage
   url: https://www.datacite.org
   icon: globe
 - name: Blog
   url: https://blog.datacite.org
   icon: rss
 - name: divider
 - name: MDS
   url: https://mds.datacite.org
   icon: database
 - name: Schema
   url: https://schema.datacite.org
   icon: file-code-o
 - name: Citation Formatter
   url: http://citation.crosscite.org
   icon: file-text-o
 - name: divider
 - name: Search
   url: https://search.datacite.org
   icon: search
 - name: OAI-PMH
   url: https://oai.datacite.org
   icon: table
 - name: Statistics
   url: https://stats.datacite.org
   icon: bar-chart
 - name: REST API
   url: https://api.datacite.org
   icon: cogs
 - name: re3data
   url: http://www.re3data.org
   icon: cubes
 - name: divider
 - name: Status
   url: http://status.datacite.org
   icon: calendar-check-o
about_links:
 - name: What we do
   url: https://www.datacite.org/mission.html
 - name: Board
   url: https://www.datacite.org/board.html
 - name: Steering groups
   url: https://www.datacite.org/steering.html
 - name: Staff
   url: https://www.datacite.org/staff.html
 - name: Job opportunities
   url: https://www.datacite.org/jobopportunities.html
services_links:
 - name: Assign DOIs
   url: https://www.datacite.org/dois.html
 - name: Metadata search
   url: https://www.datacite.org/search.html
 - name: Event data
   url: https://www.datacite.org/eventdata.html
 - name: Profiles
   url: https://www.datacite.org/profiles.html
 - name: re3data
   url: https://www.datacite.org/re3data.html
 - name: Citation formatter
   url: https://www.datacite.org/citation.html
 - name: Statistics
   url: https://www.datacite.org/stats.html
 - name: Content negotiation
   url: https://www.datacite.org/content.html
 - name: OAI-PMH
   url: https://www.datacite.org/oaipmh.html
 - name: Test environment
   url: https://www.datacite.org/test.html
resources_links:
 - name: Metadata schema
   url: https://schema.datacite.org
 - name: Technical documentation
   url: https://www.datacite.org/technical.html
 - name: Outreach material
   url: https://www.datacite.org/outreach.html
 - name: Events
   url: https://www.datacite.org/events.html
community_links:
 - name: Members
   url: https://www.datacite.org/members.html
 - name: Partners
   url: https://www.datacite.org/partners.html
 - name: Steering groups
   url: https://www.datacite.org/steering.html
 - name: Events
   url: https://www.datacite.org/events.html
contact_links:
 - name: Terms and conditions
   url: https://www.datacite.org/terms.html
 - name: Privacy policy
   url: https://www.datacite.org/privacy.html
 - name: Acknowledgements
   url: https://www.datacite.org/acknowledgments.html
social:
 - icon: twitter
   url:  https://twitter.com/datacite
   desc: Follow DataCite on Twitter
   share_url: http://twitter.com/share
   share_title: "?text="
   share_link: "&amp;url="
 - icon:  facebook
   url: https://facebook.com/???
   desc: Connect with DataCite on Facebook
   share_url: https://www.facebook.com/sharer.php
   share_title: "?t="
   share_link: "&amp;u="
